local pruebas = 0
local function prueba(nombre, funcion)
    funcion()
    pruebas = pruebas + 1
    print("OK " .. nombre)
end
local function igual(a, b)
    assert(a == b, "esperado " .. tostring(b) .. ", recibido " .. tostring(a))
end

prueba("contrato inicial accesible", function()
    local s = T.nuevo()
    igual(s.eleccion, "carga")
    igual(T.resumen(s).reputacion, 0)
end)
prueba("elecciones invalidas rechazadas", function()
    local s = T.nuevo()
    igual(T.elegir(s, "tramposo"), false)
    igual(T.elegir(s, {}), false)
    igual(T.elegir(s, nil), false)
end)
prueba("eleccion bloqueada durante el turno", function()
    local s = T.nuevo()
    igual(T.elegir(s, "express"), true)
    T.iniciar(s, 1)
    igual(T.elegir(s, "ruta"), false)
    igual(s.eleccion, "express")
end)
prueba("carga: bronce plata oro y recompensa", function()
    local s = T.nuevo()
    T.iniciar(s, 1)
    for i = 1, 6 do
        igual(T.registrar(s, 1, i, 3, 1, false), true)
        if i == 1 then igual(T.nivel(s), 1) end
        if i == 3 then igual(T.nivel(s), 2) end
    end
    igual(T.nivel(s), 3)
    local ok, premio = T.cerrar(s, 1)
    igual(ok, true)
    igual(premio, 150)
    igual(T.resumen(s).rango, "REPARTIDOR")
end)
prueba("ruta cuenta destinos no viajes repetidos", function()
    local s = T.nuevo()
    T.elegir(s, "ruta")
    T.iniciar(s, 1)
    for i = 1, 9 do T.registrar(s, 1, i, 3, 2, false) end
    igual(T.valor(s), 1)
    igual(T.nivel(s), 0)
    for i = 3, 7 do T.registrar(s, 1, 100 + i, 1, i, false) end
    igual(T.valor(s), 6)
    igual(T.nivel(s), 3)
end)
prueba("express cuenta pedidos urgentes no cajas", function()
    local s = T.nuevo()
    T.elegir(s, "express")
    T.iniciar(s, 1)
    T.registrar(s, 1, 1, 3, 1, false)
    igual(T.valor(s), 0)
    for i = 2, 6 do T.registrar(s, 1, i, 3, 1, true) end
    igual(T.valor(s), 5)
    igual(T.nivel(s), 3)
end)
prueba("repetir entrega no duplica avance", function()
    local s = T.nuevo()
    T.iniciar(s, 1)
    igual(T.registrar(s, 1, 9, 3, 1, true), true)
    igual(T.registrar(s, 1, 9, 3, 1, true), false)
    igual(s.cajas, 3)
    igual(s.urgentes, 1)
end)
prueba("cierre repetido no duplica premio", function()
    local s = T.nuevo()
    T.iniciar(s, 1)
    T.registrar(s, 1, 1, 3, 1, true)
    T.cerrar(s, 1)
    local antes = s.reputacion
    local ok, premio = T.cerrar(s, 1)
    igual(ok, false)
    igual(premio, 0)
    igual(s.reputacion, antes)
    igual(T.registrar(s, 1, 2, 3, 1, true), false)
end)
prueba("rondas viejas no cambian la actual", function()
    local s = T.nuevo()
    T.iniciar(s, 1)
    T.cerrar(s, 1)
    T.iniciar(s, 2)
    igual(T.iniciar(s, 1), false)
    igual(T.iniciar(s, 2), false)
    igual(T.registrar(s, 1, 4, 3, 1, true), false)
    igual(T.cerrar(s, 1), false)
    igual(s.activa, true)
end)
prueba("cero entregas no premia AFK", function()
    local s = T.nuevo()
    T.iniciar(s, 1)
    local ok, premio = T.cerrar(s, 1)
    igual(ok, true)
    igual(premio, 0)
end)
prueba("nuevo turno conserva reputacion y limpia objetivos", function()
    local s = T.nuevo()
    T.iniciar(s, 1)
    T.registrar(s, 1, 1, 3, 1, true)
    T.cerrar(s, 1)
    local anterior = s.ultimo
    T.elegir(s, "ruta")
    igual(s.destinos, 0)
    T.iniciar(s, 2)
    igual(s.cajas, 0)
    igual(next(s.visitados), nil)
    igual(s.reputacion, 36)
    igual(s.ultimo, anterior)
end)
prueba("jugadores independientes", function()
    local a, b = T.nuevo(), T.nuevo()
    T.iniciar(a, 1)
    T.iniciar(b, 1)
    T.registrar(a, 1, 1, 3, 1, true)
    igual(b.cajas, 0)
    igual(b.destinos, 0)
    igual(next(b.entregasVistas), nil)
end)
prueba("numeros no finitos fuera de rango y fracciones", function()
    local s = T.nuevo()
    T.iniciar(s, 1)
    for _, valor in ipairs({ 0, -1, 1.5, 4, math.huge, 0/0 }) do
        igual(T.registrar(s, 1, 20, valor, 1, false), false)
    end
    for _, valor in ipairs({ 0, -1, 1.5, 9, math.huge, 0/0 }) do
        igual(T.registrar(s, 1, 20, 1, valor, false), false)
    end
    igual(T.registrar(s, 1, 0/0, 1, 1, false), false)
    igual(T.registrar(s, 1, 20, 1, 1, "true"), false)
    igual(s.cajas, 0)
end)
prueba("limites exactos de los rangos", function()
    igual(T.rango(119), "APRENDIZ")
    igual(T.rango(120), "REPARTIDOR")
    igual(T.rango(359), "REPARTIDOR")
    igual(T.rango(360), "ESPECIALISTA")
    igual(T.rango(720), "LEYENDA")
end)
prueba("mil eventos con duplicados y premio acotado", function()
    local s = T.nuevo()
    T.iniciar(s, 1)
    for i = 1, 1000 do
        igual(T.registrar(s, 1, i, 1, i % 8 + 1, i % 2 == 0), true)
        igual(T.registrar(s, 1, i, 3, 8, true), false)
    end
    igual(s.cajas, 1000)
    igual(s.destinos, 8)
    igual(s.urgentes, 500)
    local _, premio = T.cerrar(s, 1)
    igual(premio, 150)
end)
print("PRUEBAS DE CONTRATOS: " .. pruebas)
